version: '3.9'
services:
  dashboard:
    build: .
    command: uvicorn app.dashboard.server:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=sqlite:///./researcher.db
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    working_dir: /workspace

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build: .
    command: bash -lc "celery -A app.core.celery_app.celery_app worker -l info -Q research -c 2"
    environment:
      - DATABASE_URL=sqlite:///./researcher.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - redis

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g

  searxng:
    image: searxng/searxng:latest
    environment:
      - BASE_URL=http://localhost:8080/
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m

volumes:
  qdrant_storage:
