version: '3.9'

services:
  dashboard:
    env_file:
      - ../env/prod.env
    environment:
      APP_ENV: production
      DASH_AUTH_DISABLED: "0"
    ports:
      - "${DASHBOARD_PORT:-8000}:8000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    restart: unless-stopped

  worker:
    env_file:
      - ../env/prod.env
    environment:
      APP_ENV: production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    restart: unless-stopped

  redis:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

  flower:
    env_file:
      - ../env/prod.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

