name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .
      - name: Run tests
        run: |
          pytest -q

  deep-extras:
    runs-on: ubuntu-latest
    continue-on-error: true
    services:
      qdrant:
        image: qdrant/qdrant:latest
        ports:
          - 6333:6333
      searxng:
        image: searxng/searxng:latest
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deep extras
        run: |
          python -m pip install -U pip
          pip install -e .[deep]
      - name: Smoke tests (optional)
        env:
          QDRANT_URL: http://localhost:6333
          SEARXNG_URL: http://localhost:8080
        run: |
          pytest -q app/tests/test_orchestration_basic.py -q || true
